### ISSUE TITLE
Remove useless parameter from KeepThis class

### ISSUE THREAD

**Issue by puhoshville** [puhoshville/keepthis#6]
Remove `requests_count` attribute from KeepThis class.

**Comment by duydosomething** [comment]
I can take this if it is available

**Comment by puhoshville** [comment]
@duydosomething yeap, it will be cool!)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by duydosomething** [comment]
Submitted PR #13

**Comment by puhoshville** [comment]
@duydosomething thank you!) Will check it soon!)

**Comment by duydosomething** [comment]
Glad to help! If it looks good to you, could you wait til October for approval? haha.
